@startuml button_pressed
start
:Button wird gedrückt;
if(Ist darkMode aktiv?)then(ja)
    :darkMode = inaktiv;
else(nein)
    :darkMode = aktiv;
endif
:Toggle CSS Variablen;
:Toggle HTML Elemente;
if(Ist darkMode aktiv?)then(ja)
    :Füge Bezeichnung "darkMode" zu Klassenliste hinzu;
else(nein)
    :Entferne Bezeichnung "darkMode" aus Klassenliste;
endif
:Speichern des aktuellen darkMode Zustands
im localStorgae Objekt;


stop
@enduml